version: "3"
services:
  nginx:
    build:
      context: ./proxy/nginx/
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: web
    container_name: web
    restart: always
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbredis-data:
    driver: local
  dbdata:
    driver: local
